version: "3.9"

services:
  redis:
    image: redis
    restart: always

  webapp:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"


  worker:
    restart: always
    build:
      context: .
    volumes:
      - ${PWD}/cats:/cats
    command: ['celery', '--workdir=./', '-A', 'celery_monitoring', 'worker' ]

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    volumes:
      - ./delay.sh:/delay.sh
    entrypoint: [ '/bin/sh', '-c', 'chmod +x /delay.sh && /delay.sh' ]

